export {default as BlogDetail} from '__board__/pages/BlogWriter'
export {default as BlogList} from '__board__/pages/BlogList'
export {default as BlogDetailsStandard} from '__board__/pages/BlogDetailsStandard'
export {default as BlogUpdate} from '__board__/pages/BlogUpdate'
export {default as BlogPostDetail}  from '__board__/modules/BlogPostDetail'
export {default as BlogPostList} from '__board__/modules/BlogPostList'
export {default as BlogPostWriter} from '__board__/modules/BlogPostWriter'
export {default as BlogPostUpdate} from '__board__/modules/BlogPostUpdate'